---
- name: Get Medlib from repository
  git: repo="https://github.com/medlib-v2/medlib.git" dest={{medlib_directory}} version={{medlib_version}} force=yes update=yes
  register: version_modified

- name: Install medlib dependencies (Composer)
  composer: command="install" no_dev=yes optimize_autoloader=yes working_dir={{medlib_directory}}
  when: version_modified.changed

- name: Install medlib dependencies (NPM)
  npm: path={{medlib_directory}} production=yes
  when: version_modified.changed

- name: Set writable permissions for public directories
  file: path={{item}} mode=0777 recurse=yes state=directory
  with_items:
  - "{{medlib_directory}}/storage"
  - "{{medlib_directory}}/public/upload"

- name: Check if medlib configuration file exists
  stat: path={{medlib_directory}}/.env
  register: configuration_exists

- name: Install medlib configuration file
  template: src=env.medlib.j2 dest={{medlib_directory}}/.env

- name: Run scripts to complete medlib installation
  shell: "{{item}}"
  args:
    chdir: "{{medlib_directory}}"
  with_items:
  - "php artisan clear-compiled"
  - "php artisan cache:clear"
  - "php artisan route:clear"
  - "php artisan config:clear"
  - "php artisan view:clear"
  - "php artisan optimize --force"
  - "php artisan key:generate"
  - "php artisan jwt:generate"
  - "php artisan config:cache"
  - "php artisan route:cache"
  - "php artisan migrate --force"
  - "npm install --production"

- name: Update medlib
  shell: 'printf \"\yes\" | php artisan app:update'
  args:
    chdir: "{{medlib_directory}}"
  when: (configuration_exists.stat.exists == True and version_modified.changed == True)

- name: Create medlib cron job
  cron: name="medlib schedule" job="sudo php {{medlib_directory}}/artisan schedule:run 1>> /dev/null 2>&1"

- name: Create supervisor configuration file
  template: src=medlib.conf.j2 dest=/etc/supervisor/conf.d/medlib.conf
  notify: start supervisor
